### ISSUE TITLE
Write Project Requirements Summary Document

### ISSUE THREAD

**Issue by MasSamH** [codeforamerica/brigade-playbook#21] opened 2020-08-22 16:20 UTC
### Overview
Develop requirements for BOP project to ensure that we deliver against those.

### Action Items

- [ ] Ideate on requirements 
- [ ] Review requirements with project team

**Comment by thadk** [comment] 2020-11-03 18:35
Duplicate of #23

**Closed by thadk** 2020-11-03 18:35 UTC
Labels: Product Managment, documentation
