### ISSUE TITLE
Make flagged interviews private 

### ISSUE THREAD

**Issue by Baleja** [codeforamerica/brigade-playbook#131] opened 2021-01-12 18:02 UTC
### Overview
There are some interviews that the interviewee has requested to remain fully private. 

### Action Items
- [ ] Bonnie will create another drive only accessible for Mari, jon, Thad, Bonnie & raquel
- [x] Un-share the otter ai
- [ ] Make a special folder for the transcript sheets that are not public to CFA
- [ ] Move the transcript sheets of "not public"

### Resources/Instructions
[BOP Tracking sheet](https://docs.google.com/spreadsheets/d/10uZjjrXpZH-y6wZBHZvhKgWNUBj7Xvyh9yoiqL4F_9I/edit?pli=1#gid=1930219941)

**Comment by thadk** [comment] 2021-01-14 18:42
duplicate of #132

**Closed** 2021-01-14 18:42 UTC
